name: review

on:
  pull_request:
    types: [opened, synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  review:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup-node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
          cache: "npm"

      - name: project-version-check (integration-test)
        id: actions_project_version_check
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: package.json

      - name: project-version-output-check
        run: |
          if [ -z "${{ steps.actions_project_version_check.outputs.version }}" ]; then
            exit 1
          elif [ "${{ steps.actions_project_version_check.outputs.semver }}" == "no-update"  ]; then
            exit 1
          fi

      - name: test
        run: |
          npm install
          npm test
